name: CI

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: macos-12
          #   arch: x86_64
          #   xcode: 14.2
          - os: macos-13
            arch: x86_64
            xcode: 15.2
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init
      - name: Select XCode version
        run: |
          sudo ls -1 /Applications | grep "Xcode"
          XCODE='/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer'
          sudo xcode-select -s $XCODE
      - run: make build-${{ matrix.arch }}
