name: CI

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            arch: x86_64
          - os: macos-13
            arch: x86_64
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init

      # this build requires XCode >= 15.3 and hence will fail on CI until
      # that requirement is met. For some reason, the KeyboardShortcuts
      # package requires Package.resolved from that version of XCode, so our
      # hands are tied
      # - run: make build-${{ matrix.arch }}
