name: CI

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            arch: x86_64
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init
      - run: make build-${{ matrix.arch }}
